services:
  app-dev:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - external-dev
      - internal-dev
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped

  db:
    build:
      context: ./docker/mysql
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    networks:
      - internal-dev
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./db-data/dev/data:/var/lib/mysql
      - ./db-data/dev/logs:/var/lib/mysql-bin

volumes:
  db-data:
    external: true

networks:
  external-dev:
    internal: false

  internal-dev:
    internal: true
